version: '2'
services:

  #################################################################

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  #################################################################

  owly:
    container_name: owly
    image: discord-bot/owly
    build:
      context: .
      dockerfile: Dockerfile-owly
    env_file:
      - "./.env"
    ports:
      - "3009:3009"
