FROM golang:alpine

ENV APP_HOME $GOPATH/src/github.com/adamfdl/ow_discord_leaderboard
WORKDIR $APP_HOME

ENV REDIS_SERVER_IP=redis:6379
ENV REDIS_SORTED_SET_KEY=overwatch

COPY ./ $APP_HOME
RUN go build
CMD [ "./ow_discord_leaderboard" ]