version: '2'
services:

  #################################################################

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  #################################################################

  owdl:
    container_name: owdl
    image: discord-bot/owdl
    build:
      context: .
      dockerfile: Dockerfile-owdl
    env_file:
      - "./.env"
    ports:
      - "3009:3009"
